INSERT INTO TB_INGREDIENTS(name, description) VALUES
    ('sal', 'Tempero essencial para realçar o sabor dos alimentos.'),
    ('açúcar', 'Açúcar branco utilizado como adoçante em sobremesas e bebidas.'),
    ('óleo vegetal', 'Gordura usada para cozinhar e fritar alimentos.'),
    ('azeite de oliva', 'Óleo vegetal utilizado para temperos e preparações frias e quentes.'),
    ('manteiga', 'Gordura animal usada para dar sabor e textura a pratos.'),
    ('leite', 'Laticínio líquido usado em preparações doces e salgadas.'),
    ('farinha de trigo', 'Cereal base para pães, massas e outras preparações de panificação.'),
    ('fermento em pó', 'Agente de crescimento usado em bolos e pães.'),
    ('ovos', 'Ingrediente versátil usado em uma ampla gama de preparações.'),
    ('alho', 'Tempero utilizado para dar sabor aos pratos.'),
    ('cebola', 'Ingrediente aromático que adiciona sabor e base a pratos.'),
    ('tomate', 'Vegetal fresco utilizado em molhos e saladas.'),
    ('pimenta-do-reino', 'Especiaria picante usada para temperar pratos.'),
    ('vinagre', 'Condimento ácido utilizado para temperos e marinadas.'),
    ('limão', 'Fruta cítrica usada em bebidas, marinadas e sobremesas.'),
    ('louro', 'Folha aromática usada para dar sabor a pratos de cozimento longo.'),
    ('salsa', 'Erva fresca usada para temperar e decorar pratos.'),
    ('cebolinha', 'Erva fresca com sabor suave usada para temperar e decorar.'),
    ('alho-poró', 'Vegetal de sabor suave, usado em caldos e refogados.'),
    ('coentro', 'Erva de sabor forte usada em pratos tropicais e orientais.'),
    ('manjericão', 'Erva aromática usada em molhos e pratos mediterrâneos.'),
    ('orégano', 'Erva usada especialmente em pizzas e molhos.'),
    ('alecrim', 'Erva aromática usada para temperar carnes e batatas.'),
    ('tomilho', 'Erva aromática de sabor suave, usada em assados e marinadas.'),
    ('ervas-finas', 'Mistura de ervas usada para temperar uma variedade de pratos.'),
    ('gengibre', 'Raiz picante usada em bebidas, doces e pratos orientais.'),
    ('canela', 'Especiaria doce usada em sobremesas e bebidas quentes.'),
    ('cravo-da-índia', 'Especiaria usada para aromatizar doces e marinadas.'),
    ('noz-moscada', 'Especiaria usada para temperar doces e pratos com queijo.'),
    ('páprica', 'Especiaria em pó, suave ou picante, usada em carnes e molhos.'),
    ('pimenta calabresa', 'Especiaria picante usada para dar sabor a pratos quentes.'),
    ('molho de soja', 'Condimento salgado usado em culinária oriental.'),
    ('molho inglês', 'Condimento usado para temperar carnes e molhos.'),
    ('mostarda', 'Condimento levemente picante para temperos e molhos.'),
    ('mel', 'Adoçante natural usado em sobremesas e marinadas.'),
    ('vinho branco', 'Bebida alcoólica usada para dar sabor a molhos e marinadas.'),
    ('vinho tinto', 'Bebida alcoólica usada em molhos e marinadas para carnes.'),
    ('água', 'Ingrediente essencial para diversas preparações.'),
    ('caldo de carne', 'Base líquida usada para saborizar pratos e sopas.'),
    ('caldo de frango', 'Base líquida para sopas e molhos, com sabor suave de frango.'),
    ('caldo de legumes', 'Base líquida para sopas e molhos vegetarianos.'),
    ('cream cheese', 'Laticínio cremoso usado em doces e pastas.'),
    ('creme de leite', 'Laticínio usado para dar cremosidade em doces e molhos.'),
    ('leite condensado', 'Laticínio doce usado em sobremesas e doces.'),
    ('leite de coco', 'Ingrediente de sabor tropical, usado em doces e pratos salgados.'),
    ('leite em pó', 'Laticínio desidratado usado em doces e panificação.'),
    ('chocolate em pó', 'Ingrediente usado em sobremesas e bebidas.'),
    ('chocolate meio amargo', 'Chocolate com menos açúcar, usado em doces e sobremesas.'),
    ('coco ralado', 'Fruta seca usada em sobremesas e pratos tropicais.'),
    ('baunilha', 'Condimento doce e aromático usado em sobremesas e bebidas.'),
    ('rum', 'Bebida alcoólica utilizada em coquetéis e sobremesas.'),
    ('vodka', 'Bebida alcoólica neutra usada em drinks.'),
    ('whisky', 'Bebida alcoólica com sabor marcante usada em drinks e molhos.'),
    ('cachaça', 'Bebida alcoólica usada em drinks e marinadas.'),
    ('suco de laranja', 'Suco cítrico usado em coquetéis e marinadas.'),
    ('suco de limão', 'Suco cítrico usado em bebidas, marinadas e sobremesas.'),
    ('suco de abacaxi', 'Suco tropical usado em coquetéis e marinadas.'),
    ('morango', 'Fruta doce usada em sobremesas e drinks.'),
    ('banana', 'Fruta usada em sobremesas e pratos de café da manhã.'),
    ('maçã', 'Fruta versátil usada em sobremesas e pratos salgados.'),
    ('laranja', 'Fruta cítrica usada em sucos, marinadas e sobremesas.'),
    ('uva', 'Fruta doce usada em sobremesas e sucos.'),
    ('abacaxi', 'Fruta tropical usada em sobremesas e drinks.'),
    ('manga', 'Fruta tropical doce usada em saladas e sobremesas.'),
    ('maracujá', 'Fruta tropical de sabor ácido, usada em sobremesas e sucos.'),
    ('kiwi', 'Fruta exótica de sabor ácido, usada em saladas e sobremesas.'),
    ('hortelã', 'Erva fresca usada em bebidas e sobremesas.'),
    ('água com gás', 'Base de bebidas gaseificadas e coquetéis.'),
    ('gelo', 'Ingrediente essencial para resfriar bebidas e coquetéis.'),
    ('xarope de grenadina', 'Adoçante e aromatizante para coquetéis.'),
    ('xarope de groselha', 'Adoçante usado em bebidas e sobremesas.'),
    ('cacau em pó', 'Ingrediente base para chocolates e sobremesas.'),
    ('açúcar de confeiteiro', 'Açúcar fino usado para confeitar e adoçar.'),
    ('açúcar mascavo', 'Açúcar escuro usado em doces e marinadas.'),
    ('castanha-do-pará', 'Fruta seca usada em sobremesas e receitas de panificação.'),
    ('nozes', 'Fruta seca usada em sobremesas e pratos salgados.'),
    ('amêndoas', 'Fruta seca usada em sobremesas e pratos salgados.'),
    ('pistache', 'Fruta seca usada em sobremesas e pratos salgados.'),
    ('avelãs', 'Fruta seca usada em sobremesas e chocolates.'),
    ('amendoim', 'Fruta seca usada em doces, salgados e pastas.'),
    ('tapioca', 'Derivado de mandioca usado em receitas doces e salgadas.'),
    ('fécula de batata', 'Ingrediente espessante para doces e molhos.'),
    ('amido de milho', 'Espessante usado em molhos e sobremesas.'),
    ('polvilho doce', 'Ingrediente para pães e bolos leves.'),
    ('polvilho azedo', 'Ingrediente para pães e salgados típicos.'),
    ('frango', 'Fonte de proteína usada como prato principal.'),
    ('carne bovina', 'Carne vermelha usada em pratos principais.'),
    ('carne suína', 'Carne usada em pratos principais e processados.'),
    ('peixe', 'Proteína leve usada em pratos principais e saladas.'),
    ('camarão', 'Fruto do mar usado em pratos e saladas.'),
    ('salmão', 'Peixe gordo usado em pratos e entradas.'),
    ('atum', 'Peixe usado em saladas e pratos principais.'),
    ('bacalhau', 'Peixe salgado usado em pratos tradicionais.'),
    ('salsicha', 'Carne processada usada em lanches.'),
    ('presunto', 'Carne processada usada em lanches e saladas.'),
    ('queijo parmesão', 'Queijo duro usado para gratinar e temperar pratos.'),
    ('queijo mussarela', 'Queijo usado em pizzas, massas e sanduíches.'),
    ('carne bovina - alcatra', 'Corte de carne bovina macio e saboroso, ideal para grelhados e churrascos.'),
    ('carne bovina - picanha', 'Corte nobre com camada de gordura, muito popular em churrascos e grelhados.'),
    ('carne bovina - filé mignon', 'Corte extremamente macio, perfeito para bifes e pratos refinados.'),
    ('carne bovina - contra-filé', 'Corte suculento e saboroso, ótimo para churrascos e grelhados.'),
    ('carne bovina - acém', 'Corte versátil, ideal para ensopados, cozidos e carnes desfiadas.'),
    ('carne bovina - fraldinha', 'Corte macio e de sabor marcante, ideal para grelhados e churrasco.'),
    ('carne bovina - maminha', 'Corte macio e suculento, perfeito para assados e churrasco.'),
    ('carne bovina - costela', 'Corte com ossos, ideal para cozidos e assados de longa duração.'),
    ('carne bovina - patinho', 'Corte magro, ótimo para moer, bifes e preparações rápidas.'),
    ('carne bovina - coxão mole', 'Corte macio, ideal para bifes, cozidos e assados.'),
    ('carne bovina - coxão duro', 'Corte com fibras longas, ideal para cozidos e carne de panela.'),
    ('carne bovina - lagarto', 'Corte magro, ideal para assados e preparações fatiadas, como rosbife.');

    INSERT INTO TB_MEASUREMENT_UNIT (name, abbreviation) VALUES
    ('grama','g'),
    ('kilograma','kg'),
    ('litro','L'),
    ('mililitro','ml'),
    ('unidade','un'),
    ('xicara','xc'),
    ('copo','cp'),
    ('colher de sopa','cs'),
    ('colher de cha','cc');
