INSERT INTO TB_INGREDIENTS(name, description) VALUES
    ('sal', 'Tempero essencial para realçar o sabor dos alimentos.'),
    ('açúcar', 'Açúcar branco utilizado como adoçante em sobremesas e bebidas.'),
    ('óleo vegetal', 'Gordura usada para cozinhar e fritar alimentos.'),
    ('azeite de oliva', 'Óleo vegetal utilizado para temperos e preparações frias e quentes.'),
    ('manteiga', 'Gordura animal usada para dar sabor e textura a pratos.'),
    ('leite', 'Laticínio líquido usado em preparações doces e salgadas.'),
    ('farinha de trigo', 'Cereal base para pães, massas e outras preparações de panificação.'),
    ('fermento em pó', 'Agente de crescimento usado em bolos e pães.'),
    ('ovos', 'Ingrediente versátil usado em uma ampla gama de preparações.'),
    ('alho', 'Tempero utilizado para dar sabor aos pratos.'),
    ('cebola', 'Ingrediente aromático que adiciona sabor e base a pratos.'),
    ('tomate', 'Vegetal fresco utilizado em molhos e saladas.'),
    ('pimenta-do-reino', 'Especiaria picante usada para temperar pratos.'),
    ('vinagre', 'Condimento ácido utilizado para temperos e marinadas.'),
    ('limão', 'Fruta cítrica usada em bebidas, marinadas e sobremesas.'),
    ('louro', 'Folha aromática usada para dar sabor a pratos de cozimento longo.'),
    ('salsa', 'Erva fresca usada para temperar e decorar pratos.'),
    ('cebolinha', 'Erva fresca com sabor suave usada para temperar e decorar.'),
    ('alho-poró', 'Vegetal de sabor suave, usado em caldos e refogados.'),
    ('coentro', 'Erva de sabor forte usada em pratos tropicais e orientais.'),
    ('manjericão', 'Erva aromática usada em molhos e pratos mediterrâneos.'),
    ('orégano', 'Erva usada especialmente em pizzas e molhos.'),
    ('alecrim', 'Erva aromática usada para temperar carnes e batatas.'),
    ('tomilho', 'Erva aromática de sabor suave, usada em assados e marinadas.'),
    ('ervas-finas', 'Mistura de ervas usada para temperar uma variedade de pratos.'),
    ('gengibre', 'Raiz picante usada em bebidas, doces e pratos orientais.'),
    ('canela', 'Especiaria doce usada em sobremesas e bebidas quentes.'),
    ('cravo-da-índia', 'Especiaria usada para aromatizar doces e marinadas.'),
    ('noz-moscada', 'Especiaria usada para temperar doces e pratos com queijo.'),
    ('páprica', 'Especiaria em pó, suave ou picante, usada em carnes e molhos.'),
    ('pimenta calabresa', 'Especiaria picante usada para dar sabor a pratos quentes.'),
    ('molho de soja', 'Condimento salgado usado em culinária oriental.'),
    ('molho inglês', 'Condimento usado para temperar carnes e molhos.'),
    ('mostarda', 'Condimento levemente picante para temperos e molhos.'),
    ('mel', 'Adoçante natural usado em sobremesas e marinadas.'),
    ('vinho branco', 'Bebida alcoólica usada para dar sabor a molhos e marinadas.'),
    ('vinho tinto', 'Bebida alcoólica usada em molhos e marinadas para carnes.'),
    ('água', 'Ingrediente essencial para diversas preparações.'),
    ('caldo de carne', 'Base líquida usada para saborizar pratos e sopas.'),
    ('caldo de frango', 'Base líquida para sopas e molhos, com sabor suave de frango.'),
    ('caldo de legumes', 'Base líquida para sopas e molhos vegetarianos.'),
    ('cream cheese', 'Laticínio cremoso usado em doces e pastas.'),
    ('creme de leite', 'Laticínio usado para dar cremosidade em doces e molhos.'),
    ('leite condensado', 'Laticínio doce usado em sobremesas e doces.'),
    ('leite de coco', 'Ingrediente de sabor tropical, usado em doces e pratos salgados.'),
    ('leite em pó', 'Laticínio desidratado usado em doces e panificação.'),
    ('chocolate em pó', 'Ingrediente usado em sobremesas e bebidas.'),
    ('chocolate meio amargo', 'Chocolate com menos açúcar, usado em doces e sobremesas.'),
    ('coco ralado', 'Fruta seca usada em sobremesas e pratos tropicais.'),
    ('baunilha', 'Condimento doce e aromático usado em sobremesas e bebidas.'),
    ('rum', 'Bebida alcoólica utilizada em coquetéis e sobremesas.'),
    ('vodka', 'Bebida alcoólica neutra usada em drinks.'),
    ('whisky', 'Bebida alcoólica com sabor marcante usada em drinks e molhos.'),
    ('cachaça', 'Bebida alcoólica usada em drinks e marinadas.'),
    ('suco de laranja', 'Suco cítrico usado em coquetéis e marinadas.'),
    ('suco de limão', 'Suco cítrico usado em bebidas, marinadas e sobremesas.'),
    ('suco de abacaxi', 'Suco tropical usado em coquetéis e marinadas.'),
    ('morango', 'Fruta doce usada em sobremesas e drinks.'),
    ('banana', 'Fruta usada em sobremesas e pratos de café da manhã.'),
    ('maçã', 'Fruta versátil usada em sobremesas e pratos salgados.'),
    ('laranja', 'Fruta cítrica usada em sucos, marinadas e sobremesas.'),
    ('uva', 'Fruta doce usada em sobremesas e sucos.'),
    ('abacaxi', 'Fruta tropical usada em sobremesas e drinks.'),
    ('manga', 'Fruta tropical doce usada em saladas e sobremesas.'),
    ('maracujá', 'Fruta tropical de sabor ácido, usada em sobremesas e sucos.'),
    ('kiwi', 'Fruta exótica de sabor ácido, usada em saladas e sobremesas.'),
    ('hortelã', 'Erva fresca usada em bebidas e sobremesas.'),
    ('água com gás', 'Base de bebidas gaseificadas e coquetéis.'),
    ('gelo', 'Ingrediente essencial para resfriar bebidas e coquetéis.'),
    ('xarope de grenadina', 'Adoçante e aromatizante para coquetéis.'),
    ('xarope de groselha', 'Adoçante usado em bebidas e sobremesas.'),
    ('cacau em pó', 'Ingrediente base para chocolates e sobremesas.'),
    ('açúcar de confeiteiro', 'Açúcar fino usado para confeitar e adoçar.'),
    ('açúcar mascavo', 'Açúcar escuro usado em doces e marinadas.'),
    ('castanha-do-pará', 'Fruta seca usada em sobremesas e receitas de panificação.'),
    ('nozes', 'Fruta seca usada em sobremesas e pratos salgados.'),
    ('amêndoas', 'Fruta seca usada em sobremesas e pratos salgados.'),
    ('pistache', 'Fruta seca usada em sobremesas e pratos salgados.'),
    ('avelãs', 'Fruta seca usada em sobremesas e chocolates.'),
    ('amendoim', 'Fruta seca usada em doces, salgados e pastas.'),
    ('tapioca', 'Derivado de mandioca usado em receitas doces e salgadas.'),
    ('fécula de batata', 'Ingrediente espessante para doces e molhos.'),
    ('amido de milho', 'Espessante usado em molhos e sobremesas.'),
    ('polvilho doce', 'Ingrediente para pães e bolos leves.'),
    ('polvilho azedo', 'Ingrediente para pães e salgados típicos.'),
    ('frango', 'Fonte de proteína usada como prato principal.'),
    ('carne bovina', 'Carne vermelha usada em pratos principais.'),
    ('carne suína', 'Carne usada em pratos principais e processados.'),
    ('peixe', 'Proteína leve usada em pratos principais e saladas.'),
    ('camarão', 'Fruto do mar usado em pratos e saladas.'),
    ('salmão', 'Peixe gordo usado em pratos e entradas.'),
    ('atum', 'Peixe usado em saladas e pratos principais.'),
    ('bacalhau', 'Peixe salgado usado em pratos tradicionais.'),
    ('salsicha', 'Carne processada usada em lanches.'),
    ('presunto', 'Carne processada usada em lanches e saladas.'),
    ('queijo parmesão', 'Queijo duro usado para gratinar e temperar pratos.'),
    ('queijo mussarela', 'Queijo usado em pizzas, massas e sanduíches.'),
    ('arroz', 'Grão versátil e básico em diversas culinárias, utilizado como acompanhamento e em pratos principais.'),
    ('feijão', 'Leguminosa rica em proteínas e fibras, base de pratos tradicionais.'),
    ('lentilha', 'Grão rico em proteínas, utilizado em sopas, saladas e acompanhamentos.'),
    ('grão-de-bico', 'Leguminosa utilizada em saladas, sopas e pratos mediterrâneos.'),
    ('ervilha', 'Leguminosa usada em sopas, saladas e acompanhamentos.'),
    ('soja', 'Grão rico em proteínas, utilizado em pratos vegetarianos e em forma de tofu.'),
    ('milho', 'Grão usado em pratos salgados e doces, disponível em grãos inteiros ou moídos.'),
    ('quinoa', 'Grão rico em nutrientes, utilizado como acompanhamento e em saladas.'),
    ('amaranto', 'Grão sem glúten, utilizado em saladas, pães e sobremesas.'),
    ('cevada', 'Grão usado em sopas, ensopados e pratos vegetarianos.'),
    ('trigo', 'Grão base para farinhas e em preparações de panificação.'),
    ('chia', 'Semente rica em ômega-3, usada em sobremesas e acompanhamentos.'),
    ('aveia', 'Grão integral utilizado em mingaus, pães e sobremesas.'),
    ('painço', 'Grão pequeno e nutritivo, usado em saladas e pães.'),
    ('cuscuz', 'Sêmola de trigo usada em acompanhamentos e saladas.'),
    ('farinha de mandioca', 'Farinha feita de mandioca, usada em acompanhamentos e farofas.'),
    ('farinha de milho', 'Farinha feita de milho, utilizada em pães, bolos e empanados.'),
    ('farinha de arroz', 'Farinha sem glúten, usada em preparações doces e salgadas.'),
    ('farinha de amêndoas', 'Farinha feita de amêndoas, usada em confeitaria e receitas sem glúten.'),
    ('farinha integral', 'Farinha de trigo integral, usada para pães e preparações saudáveis.'),
    ('farinha de centeio', 'Farinha usada em pães com sabor marcante e textura densa.'),
    ('farinha de grão-de-bico', 'Farinha usada em preparações vegetarianas e sem glúten.'),
    ('farinha de coco', 'Farinha de sabor suave, usada em receitas sem glúten.'),
    ('farinha de linhaça', 'Farinha usada para enriquecer pães, bolos e como substituto de ovos.'),
    ('farinha de tapioca', 'Farinha de mandioca usada em receitas leves e sem glúten.'),
    ('farinha de aveia', 'Farinha feita de aveia, usada em receitas de pães e bolos.'),
    ('farinha de trigo sarraceno', 'Farinha sem glúten, usada em panquecas e pães.'),
    ('farinha de espelta', 'Farinha antiga com sabor suave, usada em pães e massas.'),
    ('amido de mandioca', 'Ingrediente usado para dar liga em massas e preparações sem glúten.'),
    ('macarrão espaguete', 'Massa longa e fina, popular em pratos com molho de tomate e outras bases.'),
    ('macarrão penne', 'Massa tubular curta, ideal para pratos com molhos cremosos e assados.'),
    ('macarrão fusilli', 'Massa em espiral, ideal para saladas e pratos com molhos densos.'),
    ('macarrão talharim', 'Massa longa e achatada, excelente para pratos com molhos encorpados.'),
    ('macarrão fettuccine', 'Massa larga e achatada, comum em pratos com molhos de creme.'),
    ('macarrão farfalle', 'Massa em forma de laço, ótima para saladas e pratos variados.'),
    ('macarrão rigatoni', 'Massa tubular e larga, ideal para pratos gratinados e com molhos espessos.'),
    ('macarrão linguine', 'Massa longa e achatada, ótima para molhos à base de frutos do mar.'),
    ('macarrão capellini', 'Massa longa e finíssima, ideal para pratos leves e com molhos simples.'),
    ('massa de lasanha', 'Massa em folhas, usada para montar camadas com molhos e recheios.'),
    ('massa de canelone', 'Tubo de massa recheado, ideal para assados e pratos de forno.'),
    ('massa de ravioli', 'Massa recheada com carne, queijo ou legumes, servida com molhos variados.'),
    ('massa de tortellini', 'Massa recheada em formato de anel, servida com molhos ou em sopas.'),
    ('massa de nhoque', 'Massa macia feita de batata, farinha e ovo, servida com molhos.'),
    ('massa de capeletti', 'Massa recheada em formato de pequeno chapéu, popular em sopas.'),
    ('massa de tagliatelle', 'Massa longa e achatada, ótima para molhos encorpados.'),
    ('massa de conchiglioni', 'Massa em formato de concha grande, ideal para recheios e assados.'),
    ('carne bovina - alcatra', 'Corte de carne bovina macio e saboroso, ideal para grelhados e churrascos.'),
    ('carne bovina - picanha', 'Corte nobre com camada de gordura, muito popular em churrascos e grelhados.'),
    ('carne bovina - filé mignon', 'Corte extremamente macio, perfeito para bifes e pratos refinados.'),
    ('carne bovina - contra-filé', 'Corte suculento e saboroso, ótimo para churrascos e grelhados.'),
    ('carne bovina - acém', 'Corte versátil, ideal para ensopados, cozidos e carnes desfiadas.'),
    ('carne bovina - fraldinha', 'Corte macio e de sabor marcante, ideal para grelhados e churrasco.'),
    ('carne bovina - maminha', 'Corte macio e suculento, perfeito para assados e churrasco.'),
    ('carne bovina - costela', 'Corte com ossos, ideal para cozidos e assados de longa duração.'),
    ('carne bovina - patinho', 'Corte magro, ótimo para moer, bifes e preparações rápidas.'),
    ('carne bovina - coxão mole', 'Corte macio, ideal para bifes, cozidos e assados.'),
    ('carne bovina - coxão duro', 'Corte com fibras longas, ideal para cozidos e carne de panela.'),
    ('carne bovina - lagarto', 'Corte magro, ideal para assados e preparações fatiadas, como rosbife.'),
    ('cenoura', 'Legume rico em vitaminas, ideal para saladas cruas ou cozidas.'),
    ('berinjela', 'Vegetal versátil, pode ser usado em saladas ou grelhados.'),
    ('pimentão', 'Legume colorido e crocante, ótimo para dar sabor e cor às saladas.'),
    ('tomate Cereja', 'Variedade de tomate pequeno e doce, excelente para saladas frescas.'),
    ('alface', 'Folha verde que adiciona frescor e crocância às saladas, sendo uma base popular.'),
    ('rúcula', 'Folha verde com sabor picante, bastante usada em saladas e pratos leves.'),
    ('agrião', 'Folha de sabor marcante e ligeiramente amargo, muito usada em saladas.'),
    ('pepino', 'Legume refrescante, ideal para dar crocância e frescor às saladas.'),
    ('cebola Roxa', 'Cebola de sabor suave e levemente adocicado, que adiciona cor e crocância às saladas.'),
    ('azeitona', 'Fruto que pode ser verde ou preta, geralmente usado para dar um toque salgado às saladas.'),
    ('palmito', 'Ingrediente suave e crocante, comum em saladas tropicais e frescas.'),
    ('milho verde', 'Ingrediente doce e crocante, perfeito para saladas, especialmente em festas e confraternizações.'),
    ('beterraba', 'Raiz de sabor doce e terroso, pode ser consumida crua ou cozida em saladas.'),
    ('pimenta de cheiro', 'Pimenta típica do Norte e Nordeste, usada para dar sabor sem muita ardência.'),
    ('pimenta de bico', 'Pimenta pequena, muito aromática, bastante usada em pratos regionais.'),
    ('pimenta forte', 'Pimenta com sabor picante, geralmente usada em molhos e temperos mais intensos.'),
    ('cerveja preta', 'Cerveja de sabor forte, com notas de malte torrado e amargor acentuado.'),
    ('cerveja pilsen', 'Cerveja de sabor leve e refrescante, ideal para acompanhar pratos leves.'),
    ('conhaque', 'Destilado de vinho, com sabor marcante e forte, utilizado em drinks e pratos sofisticados.'),
    ('queijo mussarela ralado', 'Queijo de textura macia e sabor suave, ideal para saladas e massas.'),
    ('queijo parmesão ralado', 'Queijo de sabor intenso e salgado, utilizado para temperar e decorar pratos.'),
    ('queijo prato', 'Queijo de sabor suave e cremoso, frequentemente utilizado em sanduíches e saladas.'),
    ('queijo minas', 'Queijo branco e macio, com sabor delicado, usado em saladas ou como petisco.'),
    ('linguiça', 'Embutido feito de carne suína, geralmente temperada com alho e especiarias.'),
    ('linguiça calabresa', 'Linguiça defumada, de sabor picante, muito usada em pratos como feijão tropeiro e pizza.'),
    ('linguiça portuguesa', 'Linguiça de carne suína com um sabor levemente defumado, ideal para grelhados e saladas.'),
    ('linguiça defumada', 'Linguiça com sabor forte e defumado, que pode ser utilizada em diversos pratos.'),
    ('paio', 'Embutido feito de carne suína e temperado com alho, pimentão e outras especiarias.'),
    ('pé de porco', 'Ingrediente tradicional, muito utilizado em caldos e pratos típicos da culinária brasileira.'),
    ('orelha de porco', 'Parte do porco com textura gelatinosa, usada em pratos como feijoada e caldos.'),
    ('bacon', 'Carne defumada e salgada, geralmente usada para dar sabor e crocância em diversas preparações.'),
    ('couve', 'Folha verde rica em fibras, muito consumida em refogados e acompanhamentos como a famosa couve-manteiga.'),
    ('couve-flor', 'Legume de flores brancas, utilizado em saladas, sopas ou refogados.'),
    ('brocolis', 'Vegetal com flores verdes, rico em nutrientes, muito usado em refogados e saladas.'),
    ('lombo suino', 'Carne suína macia e saborosa, muito utilizada em assados e pratos tradicionais.'),
    ('costelinha suina', 'Parte da carne suína que contém os ossos, conhecida por seu sabor marcante e usada em churrascos e assados.');

INSERT INTO TB_MEASUREMENT_UNIT (name, abbreviation) VALUES
    ('grama', 'g'),
    ('kilograma', 'kg'),
    ('litro', 'L'),
    ('mililitro', 'ml'),
    ('unidade', 'un'),
    ('xícara', 'xíc'),
    ('copo', 'copo'),
    ('colher de sopa', 'c.s.'),
    ('colher de chá', 'c.c.'),
    ('pitada', 'pit'),
    ('fatia', 'fat'),
    ('dente', 'dente'),
    ('gotas', 'gts'),
    ('milímetro', 'mm'),
    ('polegada', 'in'),
    ('centímetro', 'cm'),
    ('punhado', 'punh'),
    ('colher de sobremesa', 'c.sb.'),
    ('pacote', 'pct'),
    ('lata', 'lata'),
    ('tablete', 'tbl'),
    ('pedaço', 'pedaço'),
    ('caixa', 'cx'),
    ('frasco', 'fr'),
    ('pote', 'pt'),
    ('galão', 'gal'),
    ('dose', 'dose'),
    ('barril', 'barril');

INSERT INTO tb_tag (tag_id, description) VALUES
    ('salgado', 'Receitas com sabor predominantemente salgado, como tortas, salgadinhos e pratos principais.'),
    ('doce', 'Receitas de sobremesas e doces, incluindo bolos, tortas e biscoitos.'),
    ('entrada', 'Receitas leves e rápidas para servir antes do prato principal.'),
    ('acompanhamento', 'Pratos servidos como complemento ao prato principal, como saladas e purês.'),
    ('coquetel', 'Bebidas alcoólicas mistas, geralmente servidas em eventos ou festas.'),
    ('vitamina', 'Bebidas nutritivas à base de frutas, vegetais e lácteos, geralmente consumidas no café da manhã.'),
    ('vegano', 'Receitas sem ingredientes de origem animal, adequadas para uma dieta vegana.'),
    ('vegetariano', 'Receitas sem carne, mas que podem conter derivados de origem animal, como laticínios e ovos.'),
    ('sem_gluten', 'Receitas livres de glúten, adequadas para pessoas com intolerância ao glúten.'),
    ('sem_lactose', 'Receitas livres de lactose, adequadas para pessoas com intolerância à lactose.'),
    ('apimentado', 'Receitas com sabor picante, para quem gosta de comidas mais fortes.'),
    ('leve', 'Receitas de baixa caloria, indicadas para uma refeição leve.'),
    ('rápido', 'Receitas rápidas e fáceis de preparar, com poucos ingredientes e etapas.'),
    ('saudável', 'Receitas nutritivas e balanceadas, focadas em ingredientes saudáveis.'),
    ('frutos_do_mar', 'Receitas que utilizam peixes, camarões, e outros frutos do mar como ingrediente principal.'),
    ('massa', 'Receitas baseadas em massas, como macarrão, lasanha e nhoque.'),
    ('sopa', 'Receitas de sopas e caldos, ideais para refeições leves e aquecedoras.'),
    ('sanduiche', 'Receitas de sanduíches, incluindo lanches rápidos e práticos.'),
    ('café_da_manhã', 'Receitas específicas para o café da manhã, como pães, panquecas e sucos.'),
    ('lanche', 'Receitas de lanches, perfeitas para comer entre as refeições principais.'),
    ('assado', 'Receitas que utilizam o forno como método principal de cozimento.'),
    ('frito', 'Receitas que utilizam o método de fritura, como salgadinhos e porções.'),
    ('grelhado', 'Receitas com alimentos grelhados, como carnes, legumes e sanduíches.'),
    ('sobremesa', 'Receitas doces servidas após a refeição principal, como tortas e pudins.'),
    ('low_carb', 'Receitas com baixo teor de carboidratos, ideal para dietas low-carb.'),
    ('fit', 'Receitas focadas em alimentação saudável e estilo de vida fitness.'),
    ('festivo', 'Receitas especiais para festas e comemorações.'),
    ('comfort_food', 'Receitas de comidas caseiras e reconfortantes, como sopas e pratos tradicionais.'),
    ('salada', 'Receitas de saladas frescas e variadas, com vegetais, frutas e/ou proteínas.'),
    ('bolo', 'Receitas de bolos, incluindo bolos simples, recheados e de festa.'),
    ('torta', 'Receitas de tortas doces ou salgadas, ideais como sobremesa ou prato principal.');

