spring:
  application:
    name: our-recipes-api
  profiles:
    active: dev

security:
  config:
    prefix: ${SECURITY_PREFIX}
    key: ${SECURITY_KEY}
    expiration: ${SECURITY_EXPIRATION}
    root: ${SECURITY_ROOT}
    root.password: ${SECURITY_ROOT_PASSWORD}

#Test
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

script:
  sql:
    path: src/main/resources/static/import.sql

#Dev
---
spring:
  config:
    activate:
      on-profile: dev


  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

script:
  sql:
    path: src/main/resources/static/import.sql

#Prod
---
spring:
  config:
    activate:
      on-profile: prod


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:db}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false

script:
  sql:
    path: src/main/resources/static/import.sql